### ISSUE TITLE
Demo Site down

### ISSUE THREAD

**Issue by theSteveMitchell** [lifegadget/ui-knob#1]
http://development.ui-knob.divshot.io/ is no longer live, since Firebase has bought Divshot.  

Great plugin!

**Comment by yankeeinlondon** [comment]
I'll move it to Firebase soon. Thanks for bringing to my attention.

**Comment by yankeeinlondon** [comment]
Ok it's up on Firebase hosting now. Links updated so closing this issue. Let me know if you have any issues.
